#.travis.yml

lenguaje: node_js
node_js:
  - "v12.18.2"
branches:
only:
  - master
before_script:
  - npm install
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - npm install
  - ng build --prod
after_sucess:
  - firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
   on_failiure: change
   on_sucess: change
